name: "Terraform Plan"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  terraform:
    name: "TF"
    uses: unir-tfm-devops/reusable-github-actions/.github/workflows/terraform-plan.yml@main
    with:
      cloud_provider: aws
    secrets: inherit
